import './globals.css';
import { Inter } from 'next/font/google';
import Player from '@/components/Player';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, modal }: { children: React.ReactNode; modal: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${inter.className}`} dir='rtl'>
        {/* main section */}
        <section className='flex'>
          <div className='hidden md:w-[30%] md:block border'>sidbar</div>
          <div className='relative w-[100%] md:w-[70%] border'>{children}</div>
        </section>

        {/* bottom section */}
        <section className='absolute bottom-0 border w-full'>
          <Player />
          <div className='md:hidden'>bottomNavigation</div>
        </section>
      </body>
    </html>
  );
}
